remote_theme: pages-themes/minimal@v0.2.0
plugins:
  - jekyll-remote-theme
  
logo: /assets/img/logo.png

title: "Data Visualization (UPC)"
description: "Website of the subject<br>Degree in Bioinformatics (UPC)"
  
